#pragma once

enum {
    GLOBAL_BUF_SIZE = 4444,
    READ_BUF_SIZE = 4096,
    ROWS_NUM = 24,
    COLS_NUM = 80,
    SUBWINDOW_ROW_OFFSET = 1,
    SUBWINDOW_COL_OFFSET = 2,
    SUBWINDOW_ROWS = 23,
    SUBWINDOW_COLS = 78,
    DIR_COLOR_PAIR = 1,
    SIZE_INFO_COLUMN = 50,
    MODIFIED_INFO_COLUMN = 66
};